server:
  port: ${FRONT50_PORT:8080}

cassandra:
  enabled: true

spinnaker:
  cassandra:
    enabled: true
    embedded: true
    cluster: CASS_SPINNAKER
    keyspace: front50
    name: default
  redis:
    enabled: false
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

swagger:
  enabled: true
  title: Spinnaker Front50 API
  description:
  contact:
  patterns:
    - /default/.*
    - /credentials.*
    - /global/.*
    - /notifications.*
    - /pipelines.*
    - /strategies.*
    - /v2/.*
